version: "3.8"

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Map container port 5173 to host port 5173
    volumes:
      - .:/app # Bind mount the project directory
      - /app/node_modules # Ignore `node_modules` in the container
    env_file:
      - .env # Load environment variables from the .env file
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable polling for file changes
    command: npm run dev
