services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:02408878@postgres-db:5432/docker-backend?schema=public
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - postgres-db
    command: npm run dev

  postgres-db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 02408878
      POSTGRES_DB: docker-backend
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
